/// <summary>
/// The spell flag list.
/// </summary>
namespace bg3_modders_multitool.Enums.ValueLists
{
    public enum SpellFlagList
    {
        None,
        HasVerbalComponent,
        HasSomaticComponent,
        IsJump,
        IsAttack,
        IsMelee,
        HasHighGroundRangeExtension,
        IsConcentration,
        AddFallDamageOnLand,
        ConcentrationIgnoresResting,
        InventorySelection,
        IsSpell,
        UnsheathedFall,
        IsEnemySpell,
        CannotTargetCharacter,
        CannotTargetItems,
        CannotTargetTerrain,
        IgnoreVisionBlock,
        Stealth,
        AddWeaponRange,
        IgnoreSilence,
        ImmediateCast,
        RangeIgnoreSourceBounds,
        RangeIgnoreTargetBounds,
        RangeIgnoreVerticalThreshold,
        NoSurprise,
        IsHarmful,
        IsTrap,
        IsDefaultWeaponAction,
        IsRequiredShield,
        TargetClosestEqualGroundSurface,
        CannotRotate,
        DontForceSheathOrUnsheath,
        CanDualWield,
        IsLinkedSpellContainer,
        Invisible,
        AllowMoveAndCast,
        SwitchSheathUnsheathOnCast,
        WildShape,
        Force1HSSubSetDuringCast,
        UnavailableInDialogs,
        TrajectoryRules,
        PickupEntityAndMove,
        Temporary,
        CantUseMusicalInstrumentForCasting,
        DontAbortPerforming,
        UseMusicalInstrumentForCasting
    }
}
