/// <summary>
/// The status group flags.
/// </summary>
namespace bg3_modders_multitool.Enums.ValueLists
{
    public enum StatusGroupFlags
    {
        SG_None,
        SG_Condition,
        SG_Blinded,
        SG_Charmed,
        SG_Cursed,
        SG_Disease,
        SG_Exhausted,
        SG_Frightened,
        SG_Incapacitated,
        SG_Invisible,
        SG_Poisoned,
        SG_Prone,
        SG_Restrained,
        SG_Stunned,
        SG_Unconscious,
        SG_Surface,
        SG_Polymorph,
        SG_Paralyzed,
        SG_Light,
        SG_Disguise,
        SG_Possessed,
        SG_Petrified,
        SG_Polymorph_BeastShape,
        SG_Polymorph_BeastShape_NPC,
        SG_Poisoned_Story_Removable,
        SG_Poisoned_Story_Nonremovable,
        SG_Charmed_Subtle,
        SG_Helpable_Condition,
        SG_Rage,
        SG_Taunted,
        SG_Approaching,
        SG_Dominated,
        SG_Fleeing,
        SG_Confused,
        SG_Mad,
        SG_DetectThoughts,
        SG_DifficultTerrain,
        SG_ScriptedPeaceBehaviour,
        SG_DropForNonMutingDialog,
        SG_WeaponCoating,
        SG_DG,
        SG_Drunk,
        SG_RemoveOnRespec,
        SG_Sleeping,
        SG_Doppelganger,
    }
}