
namespace bg3_modders_multitool.Models.StatStructures
{
    class Armor
    {
        //modifier "RootTemplate","FixedString"
        //modifier "ItemGroup","FixedString"
        //modifier "Level","ConstantInt"
        //modifier "Slot","Itemslot"
        //modifier "Requirements","Requirements"
        //modifier "UseConditions","Conditions"
        //modifier "ArmorClass","ConstantInt"
        //modifier "Durability","ConstantInt"
        //modifier "DurabilityDegradeSpeed","Qualifier"
        //modifier "ValueLevel","ConstantInt"
        //modifier "ValueUUID","Guid"
        //modifier "ValueScale","ConstantFloat"
        //modifier "ValueRounding","ConstantInt"
        //modifier "ValueOverride","ConstantInt"
        //modifier "Rarity","Rarity"
        //modifier "Weight","ConstantInt"
        //modifier "Spells","FixedString"
        //modifier "Tags","FixedString"
        //modifier "ExtraProperties","FixedString"
        //modifier "Flags","AttributeFlags"
        //modifier "DefaultBoosts","FixedString"
        //modifier "PersonalStatusImmunities","StatusIDs"
        //modifier "Boosts","FixedString"
        //modifier "Passives","FixedString"
        //modifier "ComboCategory","FixedString"
        //modifier "InventoryTab","InventoryTabs"
        //modifier "ArmorType","ArmorType"
        //modifier "ItemColor","FixedString"
        //modifier "NeedsIdentification","YesNo"
        //modifier "Charges","ConstantInt"
        //modifier "MaxCharges","ConstantInt"
        //modifier "ObjectCategory","FixedString"
        //modifier "MinAmount","ConstantInt"
        //modifier "MaxAmount","ConstantInt"
        //modifier "Priority","ConstantInt"
        //modifier "Unique","ConstantInt"
        //modifier "MinLevel","ConstantInt"
        //modifier "MaxLevel","ConstantInt"
        //modifier "Shield","YesNo"
        //modifier "Armor Class Ability","Ability"
        //modifier "Ability Modifier Cap","ConstantInt"
        //modifier "FallingHitEffect","FixedString"
        //modifier "FallingLandEffect","FixedString"
        //modifier "ColorPresetResource","FixedString"
        //modifier "Proficiency Group","ProficiencyGroupFlags"
    }
}
