
namespace bg3_modders_multitool.Models.StatStructures
{
    class Character
    {
        //modifier "Level","ConstantInt"
        //modifier "Strength","ConstantInt"
        //modifier "Dexterity","ConstantInt"
        //modifier "Constitution","ConstantInt"
        //modifier "Intelligence","ConstantInt"
        //modifier "Wisdom","ConstantInt"
        //modifier "Charisma","ConstantInt"
        //modifier "Armor","ConstantInt"
        //modifier "Vitality","ConstantInt"
        //modifier "XPReward","Guid"
        //modifier "Sight","ConstantInt"
        //modifier "Hearing","ConstantInt"
        //modifier "FOV","ConstantInt"
        //modifier "Weight","ConstantInt"
        //modifier "StepsType","StepsType"
        //modifier "ExtraProperties","FixedString"
        //modifier "Flags","AttributeFlags"
        //modifier "DefaultBoosts","FixedString"
        //modifier "PersonalStatusImmunities","StatusIDs"
        //modifier "PathInfluence","FixedString"
        //modifier "Progression Type","Progression Type"
        //modifier "ProficiencyBonus","ConstantInt"
        //modifier "SpellCastingAbility","Ability"
        //modifier "UnarmedAttackAbility","Ability"
        //modifier "ActionResources","FixedString"
        //modifier "Class","FixedString"
        //modifier "Passives","FixedString"
        //modifier "BludgeoningResistance","ResistanceFlags"
        //modifier "SlashingResistance","ResistanceFlags"
        //modifier "PiercingResistance","ResistanceFlags"
        //modifier "AcidResistance","ResistanceFlags"
        //modifier "ColdResistance","ResistanceFlags"
        //modifier "FireResistance","ResistanceFlags"
        //modifier "ForceResistance","ResistanceFlags"
        //modifier "LightningResistance","ResistanceFlags"
        //modifier "NecroticResistance","ResistanceFlags"
        //modifier "PoisonResistance","ResistanceFlags"
        //modifier "PsychicResistance","ResistanceFlags"
        //modifier "RadiantResistance","ResistanceFlags"
        //modifier "ThunderResistance","ResistanceFlags"
        //modifier "Initiative","ConstantInt"
        //modifier "Progressions","FixedString"
        //modifier "MinimumDetectionRange","FixedString"
        //modifier "DarkvisionRange","FixedString"
        //modifier "FallingHitEffect","FixedString"
        //modifier "FallingLandEffect","FixedString"
        //modifier "ArmorType","ArmorType"
        //modifier "Proficiency Group","ProficiencyGroupFlags"
    }
}
