
namespace bg3_modders_multitool.Models.StatStructures
{
    class Object
    {
        //modifier "RootTemplate","FixedString"
        //modifier "Level","ConstantInt"
        //modifier "ValueLevel","ConstantInt"
        //modifier "ValueUUID","Guid"
        //modifier "ValueScale","ConstantFloat"
        //modifier "ValueRounding","ConstantInt"
        //modifier "ValueOverride","ConstantInt"
        //modifier "Rarity","Rarity"
        //modifier "Weight","ConstantInt"
        //modifier "ComboCategory","FixedString"
        //modifier "Requirements","Requirements"
        //modifier "Vitality","ConstantInt"
        //modifier "Armor","ConstantInt"
        //modifier "Flags","AttributeFlags"
        //modifier "DefaultBoosts","FixedString"
        //modifier "PersonalStatusImmunities","StatusIDs"
        //modifier "InventoryTab","InventoryTabs"
        //modifier "AddToBottomBar","YesNo"
        //modifier "IgnoredByAI","YesNo"
        //modifier "ObjectCategory","FixedString"
        //modifier "MinAmount","ConstantInt"
        //modifier "MaxAmount","ConstantInt"
        //modifier "Priority","ConstantInt"
        //modifier "Unique","ConstantInt"
        //modifier "MinLevel","ConstantInt"
        //modifier "MaxLevel","ConstantInt"
        //modifier "UseCosts","FixedString"
        //modifier "ItemUseType","ItemUseTypes"
        //modifier "BludgeoningResistance","ResistanceFlags"
        //modifier "SlashingResistance","ResistanceFlags"
        //modifier "PiercingResistance","ResistanceFlags"
        //modifier "AcidResistance","ResistanceFlags"
        //modifier "ColdResistance","ResistanceFlags"
        //modifier "FireResistance","ResistanceFlags"
        //modifier "ForceResistance","ResistanceFlags"
        //modifier "LightningResistance","ResistanceFlags"
        //modifier "NecroticResistance","ResistanceFlags"
        //modifier "PoisonResistance","ResistanceFlags"
        //modifier "PsychicResistance","ResistanceFlags"
        //modifier "RadiantResistance","ResistanceFlags"
        //modifier "ThunderResistance","ResistanceFlags"
        //modifier "UseConditions","Conditions"
        //modifier "FallingHitEffect","FixedString"
        //modifier "FallingLandEffect","FixedString"
    }
}
