
namespace bg3_modders_multitool.Models.StatStructures
{
    class Weapon
    {
        //modifier "RootTemplate","FixedString"
        //modifier "ItemGroup","FixedString"
        //modifier "Level","ConstantInt"
        //modifier "Requirements","Requirements"
        //modifier "UseConditions","Conditions"
        //modifier "Damage Type","Damage Type"
        //modifier "Damage","FixedString"
        //modifier "Damage Range","ConstantInt"
        //modifier "WeaponRange","ConstantInt"
        //modifier "Durability","ConstantInt"
        //modifier "DurabilityDegradeSpeed","Qualifier"
        //modifier "ValueLevel","ConstantInt"
        //modifier "ValueUUID","Guid"
        //modifier "ValueScale","ConstantFloat"
        //modifier "ValueRounding","ConstantInt"
        //modifier "ValueOverride","ConstantInt"
        //modifier "Rarity","Rarity"
        //modifier "Weight","ConstantInt"
        //modifier "WeaponType","WeaponType"
        //modifier "Slot","Itemslot"
        //modifier "Projectile","FixedString"
        //modifier "IgnoreVisionBlock","YesNo"
        //modifier "ComboCategory","FixedString"
        //modifier "Spells","FixedString"
        //modifier "Tags","FixedString"
        //modifier "ExtraProperties","FixedString"
        //modifier "WeaponFunctors","StatsFunctors"
        //modifier "Flags","AttributeFlags"
        //modifier "DefaultBoosts","FixedString"
        //modifier "PersonalStatusImmunities","StatusIDs"
        //modifier "Boosts","FixedString"
        //modifier "Passives","FixedString"
        //modifier "InventoryTab","InventoryTabs"
        //modifier "NeedsIdentification","YesNo"
        //modifier "Charges","ConstantInt"
        //modifier "MaxCharges","ConstantInt"
        //modifier "ItemColor","FixedString"
        //modifier "ObjectCategory","FixedString"
        //modifier "MinAmount","ConstantInt"
        //modifier "MaxAmount","ConstantInt"
        //modifier "Priority","ConstantInt"
        //modifier "Unique","ConstantInt"
        //modifier "MinLevel","ConstantInt"
        //modifier "MaxLevel","ConstantInt"
        //modifier "Weapon Group","Weapon Group"
        //modifier "VersatileDamage","FixedString"
        //modifier "Weapon Properties","WeaponFlags"
        //modifier "FallingHitEffect","FixedString"
        //modifier "FallingLandEffect","FixedString"
        //modifier "ColorPresetResource","FixedString"
        //modifier "Proficiency Group","ProficiencyGroupFlags"
    }
}
