/// <summary>
/// The autogenerated game object model.
/// </summary>
namespace bg3_modders_multitool.Models
{
    using bg3_modders_multitool.Models.GameObjectTypes;
    using bg3_modders_multitool.Services;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Linq;
    using System.Xml;
    using System.Xml.Linq;

	public class AutoGenGameObject
    {
        public AutoGenGameObject(string file, string mapKey)
        {
			file = FileHelper.GetPath(file);

			if (File.Exists(file))
            {
                using (var fileStream = new StreamReader(file))
                using (var reader = new XmlTextReader(fileStream))
                {
                    reader.Read();
                    var found = false;
                    while (!reader.EOF && !found)
                    {
                        if (reader.NodeType == XmlNodeType.Element && reader.IsStartElement() && reader.GetAttribute("id") == "GameObjects")
                        {
                            var xml = (XElement)XNode.ReadFrom(reader);
                            var attributes = xml.Elements().Where(x => x.Name == "attribute");
                            if(attributes.Any(x => x.Attribute("value")?.Value == mapKey && x.Attribute("id").Value == "MapKey"))
                            {
                                found = true;
                                foreach (XElement attribute in attributes)
                                {
                                    var id = attribute.Attribute("id").Value;
                                    var handle = attribute.Attribute("handle")?.Value;
                                    var value = handle ?? attribute.Attribute("value").Value;
                                    var type = attribute.Attribute("type").Value;
                                    this.LoadProperty(id, type, value);
                                }
                            }
                            reader.Skip();
                        }
                        else
                        {
                            reader.Read();
                        }
                    }
                }
            }
        }

		/// <summary>
		/// Loads properties using reflection.
		/// </summary>
		/// <param name="id">The property name to match.</param>
		/// <param name="type">The property type to match.</param>
		/// <param name="value">The value to assign the matched property.</param>
		public void LoadProperty(string id, string type, string value)
		{
			if (type != null && char.IsLetter(id[0]))
			{
				var property = GetType().GetProperty(id);
				if (property != null)
				{
					LoadedProperties.Add(id);
					var propertyType = property.PropertyType;
					if (type.Contains("String"))
					{
						if (propertyType.IsEnum)
						{
							property.SetValue(this, Enum.Parse(property.PropertyType, value), null);
						}
						else
						{
							var method = propertyType.GetMethod("FromString", new Type[] { typeof(string) });
							if (method != null)
                            {
								property.SetValue(this, method.Invoke(null, new object[] { value }));
							}
							else if (propertyType == typeof(string))
							{
								property.SetValue(this, value);
							}
							else
							{
								property.SetValue(this, new StringType(value, type));
							}
						}
					}
					else
                    {
						switch(type) {
							case "int8":
								property.SetValue(this, sbyte.Parse(value));
								break;
							case "short":
								property.SetValue(this, short.Parse(value));
								break;
							case "int32":
								property.SetValue(this, int.Parse(value));
								break;
							case "uint8":
								property.SetValue(this, byte.Parse(value));
								break;
							case "uint32":
								property.SetValue(this, uint.Parse(value));
								break;
							case "uint64":
								property.SetValue(this, ulong.Parse(value));
								break;
                            case "bool":
								property.SetValue(this, bool.Parse(value));
								break;
							case "guid":
								property.SetValue(this, new Guid(value));
								break;
							case "float":
								property.SetValue(this, float.Parse(value));
								break;
							case "fvec2":
								var fvec2 = value.Split(' ').Select(v => float.Parse(v)).ToArray();
								property.SetValue(this, new Tuple<float, float>(fvec2[0], fvec2[1]));
								break;
							case "fvec3":
								var fvec3 = value.Split(' ').Select(v => float.Parse(v)).ToArray();
								property.SetValue(this, new Tuple<float, float, float>(fvec3[0], fvec3[1], fvec3[2]));
								break;
							case "fvec4":
								var fvec4 = value.Split(' ').Select(v => float.Parse(v)).ToArray();
								property.SetValue(this, new Tuple<float, float, float, float>(fvec4[0], fvec4[1], fvec4[2], fvec4[3]));
								break;
							default:
								GeneralHelper.WriteToConsole($"GameObject property [{id}] not covered.\n");
								break;
						}
                    }
				}
				else
				{
					#if DEBUG
					GeneralHelper.WriteToConsole($"GameObject property [{id}] not covered.\n");
					#endif
				}

			}
		}

		#region Properties
		private List<string> _loadedProperties = new List<string>();

		[Browsable(false)]
		public List<string> LoadedProperties {
			get { return _loadedProperties; }
			set { _loadedProperties = value; }
        }
		#endregion

		#region Autogen Properties
		private float _acceleration;

		public float Acceleration {
			get { return _acceleration; }
			set { _acceleration = value; }
		}

		private FixedString _activationGroupId;

		public FixedString ActivationGroupId {
			get { return _activationGroupId; }
			set { _activationGroupId = value; }
		}

		private FixedString _activeCharacterLightID;

		public FixedString ActiveCharacterLightID {
			get { return _activeCharacterLightID; }
			set { _activeCharacterLightID = value; }
		}

		private Guid _aiHint;

		public Guid AiHint {
			get { return _aiHint; }
			set { _aiHint = value; }
		}

		private Tuple<float, float, float> _aiPathColor;

		public Tuple<float, float, float> AiPathColor {
			get { return _aiPathColor; }
			set { _aiPathColor = value; }
		}

		private bool _allowSummonTeleport;

		public bool AllowSummonTeleport {
			get { return _allowSummonTeleport; }
			set { _allowSummonTeleport = value; }
		}

		private bool _alwaysUseDefaultLifeTime;

		public bool AlwaysUseDefaultLifeTime {
			get { return _alwaysUseDefaultLifeTime; }
			set { _alwaysUseDefaultLifeTime = value; }
		}

		private FixedString _ambientSound;

		public FixedString AmbientSound {
			get { return _ambientSound; }
			set { _ambientSound = value; }
		}

		private float _amount;

		public float Amount {
			get { return _amount; }
			set { _amount = value; }
		}

		//private int _amount;

		//public int Amount {
		//	get { return _amount; }
		//	set { _amount = value; }
		//}

		private Tuple<float, float> _angle;

		public Tuple<float, float> Angle {
			get { return _angle; }
			set { _angle = value; }
		}

		//private float _angle;

		//public float Angle {
		//	get { return _angle; }
		//	set { _angle = value; }
		//}

		private float _angleCutoff;

		public float AngleCutoff {
			get { return _angleCutoff; }
			set { _angleCutoff = value; }
		}

		private FixedString _animationSetResourceID;

		public FixedString AnimationSetResourceID {
			get { return _animationSetResourceID; }
			set { _animationSetResourceID = value; }
		}

		private FixedString _anubisConfigName;

		public FixedString AnubisConfigName {
			get { return _anubisConfigName; }
			set { _anubisConfigName = value; }
		}

		private FixedString _archetype;

		public FixedString Archetype {
			get { return _archetype; }
			set { _archetype = value; }
		}

		private float _attenuationScale;

		public float AttenuationScale {
			get { return _attenuationScale; }
			set { _attenuationScale = value; }
		}

		private byte _auxBus1;

		public byte AuxBus1 {
			get { return _auxBus1; }
			set { _auxBus1 = value; }
		}

		private byte _auxBus2;

		public byte AuxBus2 {
			get { return _auxBus2; }
			set { _auxBus2 = value; }
		}

		private byte _auxBus3;

		public byte AuxBus3 {
			get { return _auxBus3; }
			set { _auxBus3 = value; }
		}

		private byte _auxBus4;

		public byte AuxBus4 {
			get { return _auxBus4; }
			set { _auxBus4 = value; }
		}

		private bool _avoidTraps;

		public bool AvoidTraps {
			get { return _avoidTraps; }
			set { _avoidTraps = value; }
		}

		private FixedString _beamFX;

		public FixedString BeamFX {
			get { return _beamFX; }
			set { _beamFX = value; }
		}

		private FixedString _bloodSurfaceType;

		public FixedString BloodSurfaceType {
			get { return _bloodSurfaceType; }
			set { _bloodSurfaceType = value; }
		}

		private FixedString _bloodType;

		public FixedString BloodType {
			get { return _bloodType; }
			set { _bloodType = value; }
		}

		private Tuple<float, float, float> _cameraOffset;

		public Tuple<float, float, float> CameraOffset {
			get { return _cameraOffset; }
			set { _cameraOffset = value; }
		}

		private bool _canBeMoved;

		public bool CanBeMoved {
			get { return _canBeMoved; }
			set { _canBeMoved = value; }
		}

		private bool _canBePickedUp;

		public bool CanBePickedUp {
			get { return _canBePickedUp; }
			set { _canBePickedUp = value; }
		}

		private bool _canBeTeleported;

		public bool CanBeTeleported {
			get { return _canBeTeleported; }
			set { _canBeTeleported = value; }
		}

		private bool _canClickThrough;

		public bool CanClickThrough {
			get { return _canClickThrough; }
			set { _canClickThrough = value; }
		}

		private bool _canClimbLadders;

		public bool CanClimbLadders {
			get { return _canClimbLadders; }
			set { _canClimbLadders = value; }
		}

		private bool _canClimbOn;

		public bool CanClimbOn {
			get { return _canClimbOn; }
			set { _canClimbOn = value; }
		}

		private bool _canEnterCombat;

		public bool CanEnterCombat {
			get { return _canEnterCombat; }
			set { _canEnterCombat = value; }
		}

		private bool _canFight;

		public bool CanFight {
			get { return _canFight; }
			set { _canFight = value; }
		}

		private bool _canJoinCombat;

		public bool CanJoinCombat {
			get { return _canJoinCombat; }
			set { _canJoinCombat = value; }
		}

		private bool _canLongRest;

		public bool CanLongRest {
			get { return _canLongRest; }
			set { _canLongRest = value; }
		}

		private bool _canOpenDoors;

		public bool CanOpenDoors {
			get { return _canOpenDoors; }
			set { _canOpenDoors = value; }
		}

		private bool _canSeeThrough;

		public bool CanSeeThrough {
			get { return _canSeeThrough; }
			set { _canSeeThrough = value; }
		}

		private bool _canShootThrough;

		public bool CanShootThrough {
			get { return _canShootThrough; }
			set { _canShootThrough = value; }
		}

		private byte _captureType;

		public byte CaptureType {
			get { return _captureType; }
			set { _captureType = value; }
		}

		private FixedString _castBone;

		public FixedString CastBone {
			get { return _castBone; }
			set { _castBone = value; }
		}

		private bool _castShadow;

		public bool CastShadow {
			get { return _castShadow; }
			set { _castShadow = value; }
		}

		private FixedString _characterVisualResourceID;

		public FixedString CharacterVisualResourceID {
			get { return _characterVisualResourceID; }
			set { _characterVisualResourceID = value; }
		}

		private bool _collideWithCamera;

		public bool CollideWithCamera {
			get { return _collideWithCamera; }
			set { _collideWithCamera = value; }
		}

		private Tuple<float, float, float> _color;

		public Tuple<float, float, float> Color {
			get { return _color; }
			set { _color = value; }
		}

		private Tuple<float, float, float, float> _color4;

		public Tuple<float, float, float, float> Color4 {
			get { return _color4; }
			set { _color4 = value; }
		}

		private FixedString _combatGroupID;

		public FixedString CombatGroupID {
			get { return _combatGroupID; }
			set { _combatGroupID = value; }
		}

		private LSString _combatName;

		public LSString CombatName {
			get { return _combatName; }
			set { _combatName = value; }
		}

		private byte _coverAmount;

		public byte CoverAmount {
			get { return _coverAmount; }
			set { _coverAmount = value; }
		}

		private bool _crowdAreItemsAllowed;

		public bool CrowdAreItemsAllowed {
			get { return _crowdAreItemsAllowed; }
			set { _crowdAreItemsAllowed = value; }
		}

		private bool _crowdSystemEnabled;

		public bool CrowdSystemEnabled {
			get { return _crowdSystemEnabled; }
			set { _crowdSystemEnabled = value; }
		}

		private float _deathRaycastMaxLength;

		public float DeathRaycastMaxLength {
			get { return _deathRaycastMaxLength; }
			set { _deathRaycastMaxLength = value; }
		}

		private float _deathRaycastMinLength;

		public float DeathRaycastMinLength {
			get { return _deathRaycastMinLength; }
			set { _deathRaycastMinLength = value; }
		}

		private FixedString _decalMaterial;

		public FixedString DecalMaterial {
			get { return _decalMaterial; }
			set { _decalMaterial = value; }
		}

		private byte _decalType;

		public byte DecalType {
			get { return _decalType; }
			set { _decalType = value; }
		}

		private FixedString _defaultDialog;

		public FixedString DefaultDialog {
			get { return _defaultDialog; }
			set { _defaultDialog = value; }
		}

		private float _defaultLifeTime;

		public float DefaultLifeTime {
			get { return _defaultLifeTime; }
			set { _defaultLifeTime = value; }
		}

		private FixedString _defaultState;

		public FixedString DefaultState {
			get { return _defaultState; }
			set { _defaultState = value; }
		}

		//private byte _defaultState;

		//public byte DefaultState {
		//	get { return _defaultState; }
		//	set { _defaultState = value; }
		//}

		private TranslatedString _description;

		public TranslatedString Description {
			get { return _description; }
			set { _description = value; }
		}

		private bool _destroyed;

		public bool Destroyed {
			get { return _destroyed; }
			set { _destroyed = value; }
		}

		private bool _destroyTrailFXOnImpact;

		public bool DestroyTrailFXOnImpact {
			get { return _destroyTrailFXOnImpact; }
			set { _destroyTrailFXOnImpact = value; }
		}

		private bool _detachBeam;

		public bool DetachBeam {
			get { return _detachBeam; }
			set { _detachBeam = value; }
		}

		private LSString _devComment;

		public LSString DevComment {
			get { return _devComment; }
			set { _devComment = value; }
		}

		private Tuple<float, float, float> _dimensions;

		public Tuple<float, float, float> Dimensions {
			get { return _dimensions; }
			set { _dimensions = value; }
		}

		private bool _disableEquipping;

		public bool DisableEquipping {
			get { return _disableEquipping; }
			set { _disableEquipping = value; }
		}

		private int _disarmDC;

		public int DisarmDC {
			get { return _disarmDC; }
			set { _disarmDC = value; }
		}

		private TranslatedString _displayName;

		public TranslatedString DisplayName {
			get { return _displayName; }
			set { _displayName = value; }
		}

		private float _dOFAperature;

		public float DOFAperature {
			get { return _dOFAperature; }
			set { _dOFAperature = value; }
		}

		private float _dOFFarOnly;

		public float DOFFarOnly {
			get { return _dOFFarOnly; }
			set { _dOFFarOnly = value; }
		}

		private float _dOFFarSharpDistance;

		public float DOFFarSharpDistance {
			get { return _dOFFarSharpDistance; }
			set { _dOFFarSharpDistance = value; }
		}

		private float _dOFFocalDistance;

		public float DOFFocalDistance {
			get { return _dOFFocalDistance; }
			set { _dOFFocalDistance = value; }
		}

		private float _dOFNearOnly;

		public float DOFNearOnly {
			get { return _dOFNearOnly; }
			set { _dOFNearOnly = value; }
		}

		private float _dOFNearSharpDistance;

		public float DOFNearSharpDistance {
			get { return _dOFNearSharpDistance; }
			set { _dOFNearSharpDistance = value; }
		}

		private FixedString _dropSound;

		public FixedString DropSound {
			get { return _dropSound; }
			set { _dropSound = value; }
		}

		private bool _enabled;

		public bool Enabled {
			get { return _enabled; }
			set { _enabled = value; }
		}

		private FixedString _enterEvent;

		public FixedString EnterEvent {
			get { return _enterEvent; }
			set { _enterEvent = value; }
		}

		private FixedString _equipment;

		public FixedString Equipment {
			get { return _equipment; }
			set { _equipment = value; }
		}

		private Guid _equipmentRace;

		public Guid EquipmentRace {
			get { return _equipmentRace; }
			set { _equipmentRace = value; }
		}

		private Guid _equipmentTypeID;

		public Guid EquipmentTypeID {
			get { return _equipmentTypeID; }
			set { _equipmentTypeID = value; }
		}

		private FixedString _equipSound;

		public FixedString EquipSound {
			get { return _equipSound; }
			set { _equipSound = value; }
		}

		private FixedString _explodedResourceID;

		public FixedString ExplodedResourceID {
			get { return _explodedResourceID; }
			set { _explodedResourceID = value; }
		}

		private Guid _explorationReward;

		public Guid ExplorationReward {
			get { return _explorationReward; }
			set { _explorationReward = value; }
		}

		private FixedString _explosionFX;

		public FixedString ExplosionFX {
			get { return _explosionFX; }
			set { _explosionFX = value; }
		}

		private Tuple<float, float, float> _extents;

		public Tuple<float, float, float> Extents {
			get { return _extents; }
			set { _extents = value; }
		}

		private Guid _faction;

		public Guid Faction {
			get { return _faction; }
			set { _faction = value; }
		}

		private bool _fadeable;

		public bool Fadeable {
			get { return _fadeable; }
			set { _fadeable = value; }
		}

		private FixedString _fadeGroup;

		public FixedString FadeGroup {
			get { return _fadeGroup; }
			set { _fadeGroup = value; }
		}

		private bool _fadeIn;

		public bool FadeIn {
			get { return _fadeIn; }
			set { _fadeIn = value; }
		}

		private float _fadeInSpeed;

		public float FadeInSpeed {
			get { return _fadeInSpeed; }
			set { _fadeInSpeed = value; }
		}

		private float _fadeOutSpeed;

		public float FadeOutSpeed {
			get { return _fadeOutSpeed; }
			set { _fadeOutSpeed = value; }
		}

		private float _fadeTime;

		public float FadeTime {
			get { return _fadeTime; }
			set { _fadeTime = value; }
		}

		private float _fallDamageMultiplier;

		public float FallDamageMultiplier {
			get { return _fallDamageMultiplier; }
			set { _fallDamageMultiplier = value; }
		}

		private int _flag;

		public int Flag {
			get { return _flag; }
			set { _flag = value; }
		}

		private bool _floating;

		public bool Floating {
			get { return _floating; }
			set { _floating = value; }
		}

		private FixedString _foleyLongResourceID;

		public FixedString FoleyLongResourceID {
			get { return _foleyLongResourceID; }
			set { _foleyLongResourceID = value; }
		}

		private FixedString _foleyMediumResourceID;

		public FixedString FoleyMediumResourceID {
			get { return _foleyMediumResourceID; }
			set { _foleyMediumResourceID = value; }
		}

		private FixedString _foleyShortResourceID;

		public FixedString FoleyShortResourceID {
			get { return _foleyShortResourceID; }
			set { _foleyShortResourceID = value; }
		}

		private bool _forceUnsheathSkills;

		public bool ForceUnsheathSkills {
			get { return _forceUnsheathSkills; }
			set { _forceUnsheathSkills = value; }
		}

		private float _fOV;

		public float FOV {
			get { return _fOV; }
			set { _fOV = value; }
		}

		private bool _freezeGravity;

		public bool FreezeGravity {
			get { return _freezeGravity; }
			set { _freezeGravity = value; }
		}

		private float _gain;

		public float Gain {
			get { return _gain; }
			set { _gain = value; }
		}

		private LSString _generatePortrait;

		public LSString GeneratePortrait {
			get { return _generatePortrait; }
			set { _generatePortrait = value; }
		}

		private bool _generateRunningDeepWater;

		public bool GenerateRunningDeepWater {
			get { return _generateRunningDeepWater; }
			set { _generateRunningDeepWater = value; }
		}

		private FixedString _ghostTemplate;

		public FixedString GhostTemplate {
			get { return _ghostTemplate; }
			set { _ghostTemplate = value; }
		}

		private LSString _groundImpactFX;

		public LSString GroundImpactFX {
			get { return _groundImpactFX; }
			set { _groundImpactFX = value; }
		}

		private uint _groupID;

		public uint GroupID {
			get { return _groupID; }
			set { _groupID = value; }
		}

		private bool _hardcoreOnly;

		public bool HardcoreOnly {
			get { return _hardcoreOnly; }
			set { _hardcoreOnly = value; }
		}

		private bool _hasGameplayValue;

		public bool HasGameplayValue {
			get { return _hasGameplayValue; }
			set { _hasGameplayValue = value; }
		}

		private bool _hasPlayerApprovalRating;

		public bool HasPlayerApprovalRating {
			get { return _hasPlayerApprovalRating; }
			set { _hasPlayerApprovalRating = value; }
		}

		private float _height;

		public float Height {
			get { return _height; }
			set { _height = value; }
		}

		private bool _hierarchyOnlyFade;

		public bool HierarchyOnlyFade {
			get { return _hierarchyOnlyFade; }
			set { _hierarchyOnlyFade = value; }
		}

		private Guid _hLOD;

		public Guid HLOD {
			get { return _hLOD; }
			set { _hLOD = value; }
		}

		private bool _hostile;

		public bool Hostile {
			get { return _hostile; }
			set { _hostile = value; }
		}

		private FixedString _icon;

		public FixedString Icon {
			get { return _icon; }
			set { _icon = value; }
		}

		private bool _ignoreGenerics;

		public bool IgnoreGenerics {
			get { return _ignoreGenerics; }
			set { _ignoreGenerics = value; }
		}

		private FixedString _impactFX;

		public FixedString ImpactFX {
			get { return _impactFX; }
			set { _impactFX = value; }
		}

		private FixedString _impactSound;

		public FixedString ImpactSound {
			get { return _impactSound; }
			set { _impactSound = value; }
		}

		private bool _infiniteCapture;

		public bool InfiniteCapture {
			get { return _infiniteCapture; }
			set { _infiniteCapture = value; }
		}

		private bool _influenceTreasureLevel;

		public bool InfluenceTreasureLevel {
			get { return _influenceTreasureLevel; }
			set { _influenceTreasureLevel = value; }
		}

		private float _intensity;

		public float Intensity {
			get { return _intensity; }
			set { _intensity = value; }
		}

		private FixedString _inventoryMoveSound;

		public FixedString InventoryMoveSound {
			get { return _inventoryMoveSound; }
			set { _inventoryMoveSound = value; }
		}

		private byte _inventoryType;

		public byte InventoryType {
			get { return _inventoryType; }
			set { _inventoryType = value; }
		}

		private bool _isAnchor;

		public bool IsAnchor {
			get { return _isAnchor; }
			set { _isAnchor = value; }
		}

		private bool _isBlocker;

		public bool IsBlocker {
			get { return _isBlocker; }
			set { _isBlocker = value; }
		}

		private bool _isBoss;

		public bool IsBoss {
			get { return _isBoss; }
			set { _isBoss = value; }
		}

		private bool _isDecorative;

		public bool IsDecorative {
			get { return _isDecorative; }
			set { _isDecorative = value; }
		}

		private bool _isEquipmentLootable;

		public bool IsEquipmentLootable {
			get { return _isEquipmentLootable; }
			set { _isEquipmentLootable = value; }
		}

		private bool _isFlickering;

		public bool IsFlickering {
			get { return _isFlickering; }
			set { _isFlickering = value; }
		}

		private bool _isForcedType;

		public bool IsForcedType {
			get { return _isForcedType; }
			set { _isForcedType = value; }
		}

		private bool _isGlobal;

		public bool IsGlobal {
			get { return _isGlobal; }
			set { _isGlobal = value; }
		}

		private bool _isHuge;

		public bool IsHuge {
			get { return _isHuge; }
			set { _isHuge = value; }
		}

		private bool _isInspector;

		public bool IsInspector {
			get { return _isInspector; }
			set { _isInspector = value; }
		}

		private bool _isInteractionDisabled;

		public bool IsInteractionDisabled {
			get { return _isInteractionDisabled; }
			set { _isInteractionDisabled = value; }
		}

		private bool _isKey;

		public bool IsKey {
			get { return _isKey; }
			set { _isKey = value; }
		}

		private bool _isLootable;

		public bool IsLootable {
			get { return _isLootable; }
			set { _isLootable = value; }
		}

		private bool _isMoving;

		public bool IsMoving {
			get { return _isMoving; }
			set { _isMoving = value; }
		}

		private bool _isPlatformOwner;

		public bool IsPlatformOwner {
			get { return _isPlatformOwner; }
			set { _isPlatformOwner = value; }
		}

		private bool _isPlayer;

		public bool IsPlayer {
			get { return _isPlayer; }
			set { _isPlayer = value; }
		}

		private bool _isPointerBlocker;

		public bool IsPointerBlocker {
			get { return _isPointerBlocker; }
			set { _isPointerBlocker = value; }
		}

		private bool _isPortalProhibitedToPlayers;

		public bool IsPortalProhibitedToPlayers {
			get { return _isPortalProhibitedToPlayers; }
			set { _isPortalProhibitedToPlayers = value; }
		}

		private bool _isPublicDomain;

		public bool IsPublicDomain {
			get { return _isPublicDomain; }
			set { _isPublicDomain = value; }
		}

		private bool _isScrollingObject;

		public bool IsScrollingObject {
			get { return _isScrollingObject; }
			set { _isScrollingObject = value; }
		}

		private bool _isShadowProxy;

		public bool IsShadowProxy {
			get { return _isShadowProxy; }
			set { _isShadowProxy = value; }
		}

		private bool _isSourceContainer;

		public bool IsSourceContainer {
			get { return _isSourceContainer; }
			set { _isSourceContainer = value; }
		}

		private bool _isSurfaceBlocker;

		public bool IsSurfaceBlocker {
			get { return _isSurfaceBlocker; }
			set { _isSurfaceBlocker = value; }
		}

		private bool _isSurfaceCloudBlocker;

		public bool IsSurfaceCloudBlocker {
			get { return _isSurfaceCloudBlocker; }
			set { _isSurfaceCloudBlocker = value; }
		}

		private bool _isTrap;

		public bool IsTrap {
			get { return _isTrap; }
			set { _isTrap = value; }
		}

		private FixedString _key;

		public FixedString Key {
			get { return _key; }
			set { _key = value; }
		}

		private float _ladderAttachSpeed;

		public float LadderAttachSpeed {
			get { return _ladderAttachSpeed; }
			set { _ladderAttachSpeed = value; }
		}

		private float _ladderDetachSpeed;

		public float LadderDetachSpeed {
			get { return _ladderDetachSpeed; }
			set { _ladderDetachSpeed = value; }
		}

		private float _ladderLoopSpeed;

		public float LadderLoopSpeed {
			get { return _ladderLoopSpeed; }
			set { _ladderLoopSpeed = value; }
		}

		private uint _layer;

		public uint Layer {
			get { return _layer; }
			set { _layer = value; }
		}

		private FixedString _leaveEvent;

		public FixedString LeaveEvent {
			get { return _leaveEvent; }
			set { _leaveEvent = value; }
		}

		private bool _lerp;

		public bool Lerp {
			get { return _lerp; }
			set { _lerp = value; }
		}

		private FixedString _levelName;

		public FixedString LevelName {
			get { return _levelName; }
			set { _levelName = value; }
		}

		private int _levelOverride;

		public int LevelOverride {
			get { return _levelOverride; }
			set { _levelOverride = value; }
		}

		private float _lifeTime;

		public float LifeTime {
			get { return _lifeTime; }
			set { _lifeTime = value; }
		}

		private byte _lightChannel;

		public byte LightChannel {
			get { return _lightChannel; }
			set { _lightChannel = value; }
		}

		private byte _lightChannelFlag;

		public byte LightChannelFlag {
			get { return _lightChannelFlag; }
			set { _lightChannelFlag = value; }
		}

		private FixedString _lightID;

		public FixedString LightID {
			get { return _lightID; }
			set { _lightID = value; }
		}

		private byte _lightProbeShape;

		public byte LightProbeShape {
			get { return _lightProbeShape; }
			set { _lightProbeShape = value; }
		}

		private byte _lightProbeType;

		public byte LightProbeType {
			get { return _lightProbeType; }
			set { _lightProbeType = value; }
		}

		private byte _lightType;

		public byte LightType {
			get { return _lightType; }
			set { _lightType = value; }
		}

		private bool _lightVolume;

		public bool LightVolume {
			get { return _lightVolume; }
			set { _lightVolume = value; }
		}

		private int _lightVolumeSamplesCount;

		public int LightVolumeSamplesCount {
			get { return _lightVolumeSamplesCount; }
			set { _lightVolumeSamplesCount = value; }
		}

		private FixedString _lightVolumeTexture;

		public FixedString LightVolumeTexture {
			get { return _lightVolumeTexture; }
			set { _lightVolumeTexture = value; }
		}

		private int _lockDC;

		public int LockDC {
			get { return _lockDC; }
			set { _lockDC = value; }
		}

		private FixedString _longHair;

		public FixedString LongHair {
			get { return _longHair; }
			set { _longHair = value; }
		}

		private bool _looping;

		public bool Looping {
			get { return _looping; }
			set { _looping = value; }
		}

		private FixedString _loopSound;

		public FixedString LoopSound {
			get { return _loopSound; }
			set { _loopSound = value; }
		}

		private FixedString _mapKey;

		public FixedString MapKey {
			get { return _mapKey; }
			set { _mapKey = value; }
		}

		private FixedString _material;

		public FixedString Material {
			get { return _material; }
			set { _material = value; }
		}

		private byte _materialType;

		public byte MaterialType {
			get { return _materialType; }
			set { _materialType = value; }
		}

		private short _maxAttenuation;

		public short MaxAttenuation {
			get { return _maxAttenuation; }
			set { _maxAttenuation = value; }
		}

		private float _maxChasmHeightOffset;

		public float MaxChasmHeightOffset {
			get { return _maxChasmHeightOffset; }
			set { _maxChasmHeightOffset = value; }
		}

		private uint _maxChasmTiles;

		public uint MaxChasmTiles {
			get { return _maxChasmTiles; }
			set { _maxChasmTiles = value; }
		}

		private float _maxPathRadius;

		public float MaxPathRadius {
			get { return _maxPathRadius; }
			set { _maxPathRadius = value; }
		}

		private int _maxStackAmount;

		public int maxStackAmount {
			get { return _maxStackAmount; }
			set { _maxStackAmount = value; }
		}

		private FixedString _meshProxy;

		public FixedString MeshProxy {
			get { return _meshProxy; }
			set { _meshProxy = value; }
		}

		private float _movementAmount;

		public float MovementAmount {
			get { return _movementAmount; }
			set { _movementAmount = value; }
		}

		private float _movementSpeed;

		public float MovementSpeed {
			get { return _movementSpeed; }
			set { _movementSpeed = value; }
		}

		private LSString _name;

		public LSString Name {
			get { return _name; }
			set { _name = value; }
		}

		private bool _needsImpactSFX;

		public bool NeedsImpactSFX {
			get { return _needsImpactSFX; }
			set { _needsImpactSFX = value; }
		}

		private float _normalBlendingFactor;

		public float NormalBlendingFactor {
			get { return _normalBlendingFactor; }
			set { _normalBlendingFactor = value; }
		}

		private bool _notHardcore;

		public bool NotHardcore {
			get { return _notHardcore; }
			set { _notHardcore = value; }
		}

		private byte _obscuredStateOverride;

		public byte ObscuredStateOverride {
			get { return _obscuredStateOverride; }
			set { _obscuredStateOverride = value; }
		}

		private float _occlusion;

		public float Occlusion {
			get { return _occlusion; }
			set { _occlusion = value; }
		}

		private Tuple<float, float> _offset;

		public Tuple<float, float> offset {
			get { return _offset; }
			set { _offset = value; }
		}

		private float _onEnterDistanceOverride;

		public float OnEnterDistanceOverride {
			get { return _onEnterDistanceOverride; }
			set { _onEnterDistanceOverride = value; }
		}

		private float _onMoveDistanceOverride;

		public float OnMoveDistanceOverride {
			get { return _onMoveDistanceOverride; }
			set { _onMoveDistanceOverride = value; }
		}

		private TranslatedString _onUseDescription;

		public TranslatedString OnUseDescription {
			get { return _onUseDescription; }
			set { _onUseDescription = value; }
		}

		private float _opacity;

		public float Opacity {
			get { return _opacity; }
			set { _opacity = value; }
		}

		private FixedString _owner;

		public FixedString owner {
			get { return _owner; }
			set { _owner = value; }
		}

		private Guid _parentGuid;

		public Guid ParentGuid {
			get { return _parentGuid; }
			set { _parentGuid = value; }
		}

		private Guid _parentGUID;

		public Guid ParentGUID {
			get { return _parentGUID; }
			set { _parentGUID = value; }
		}

		private FixedString _parentTemplateId;

		public FixedString ParentTemplateId {
			get { return _parentTemplateId; }
			set { _parentTemplateId = value; }
		}

		private FixedString _parentTrigger;

		public FixedString ParentTrigger {
			get { return _parentTrigger; }
			set { _parentTrigger = value; }
		}

		private float _pathMaxArcDist;

		public float PathMaxArcDist {
			get { return _pathMaxArcDist; }
			set { _pathMaxArcDist = value; }
		}

		private float _pathMinArcDist;

		public float PathMinArcDist {
			get { return _pathMinArcDist; }
			set { _pathMinArcDist = value; }
		}

		private float _pathRadius;

		public float PathRadius {
			get { return _pathRadius; }
			set { _pathRadius = value; }
		}

		private uint _pathRepeat;

		public uint PathRepeat {
			get { return _pathRepeat; }
			set { _pathRepeat = value; }
		}

		private float _pathShift;

		public float PathShift {
			get { return _pathShift; }
			set { _pathShift = value; }
		}

		private bool _persistent;

		public bool Persistent {
			get { return _persistent; }
			set { _persistent = value; }
		}

		private bool _physicsFollowAnimation;

		public bool PhysicsFollowAnimation {
			get { return _physicsFollowAnimation; }
			set { _physicsFollowAnimation = value; }
		}

		private FixedString _physicsOpenTemplate;

		public FixedString PhysicsOpenTemplate {
			get { return _physicsOpenTemplate; }
			set { _physicsOpenTemplate = value; }
		}

		private FixedString _physicsTemplate;

		public FixedString PhysicsTemplate {
			get { return _physicsTemplate; }
			set { _physicsTemplate = value; }
		}

		private int _physicsType;

		public int PhysicsType {
			get { return _physicsType; }
			set { _physicsType = value; }
		}

		private FixedString _pickupSound;

		public FixedString PickupSound {
			get { return _pickupSound; }
			set { _pickupSound = value; }
		}

		private byte _player;

		public byte Player {
			get { return _player; }
			set { _player = value; }
		}

		private bool _preExpose;

		public bool PreExpose {
			get { return _preExpose; }
			set { _preExpose = value; }
		}

		private FixedString _previewPathImpactFX;

		public FixedString PreviewPathImpactFX {
			get { return _previewPathImpactFX; }
			set { _previewPathImpactFX = value; }
		}

		private FixedString _previewPathMaterial;

		public FixedString PreviewPathMaterial {
			get { return _previewPathMaterial; }
			set { _previewPathMaterial = value; }
		}

		private float _previewPathRadius;

		public float PreviewPathRadius {
			get { return _previewPathRadius; }
			set { _previewPathRadius = value; }
		}

		private byte _projectilePath;

		public byte ProjectilePath {
			get { return _projectilePath; }
			set { _projectilePath = value; }
		}

		//private sbyte _race;

		//public sbyte Race {
		//	get { return _race; }
		//	set { _race = value; }
		//}

		private Guid _race;

		public Guid Race {
			get { return _race; }
			set { _race = value; }
		}

		private float _radius;

		public float Radius {
			get { return _radius; }
			set { _radius = value; }
		}

		private FixedString _ragdollTemplate;

		public FixedString RagdollTemplate {
			get { return _ragdollTemplate; }
			set { _ragdollTemplate = value; }
		}

		private ulong _random;

		public ulong Random {
			get { return _random; }
			set { _random = value; }
		}

		private uint _readinessFlags;

		public uint ReadinessFlags {
			get { return _readinessFlags; }
			set { _readinessFlags = value; }
		}

		private bool _recieveDecal;

		public bool RecieveDecal {
			get { return _recieveDecal; }
			set { _recieveDecal = value; }
		}

		private bool _regionCameraLock;

		public bool RegionCameraLock {
			get { return _regionCameraLock; }
			set { _regionCameraLock = value; }
		}

		private bool _regionCameraLockPos;

		public bool RegionCameraLockPos {
			get { return _regionCameraLockPos; }
			set { _regionCameraLockPos = value; }
		}

		private bool _regionMaskRegionInWorld;

		public bool RegionMaskRegionInWorld {
			get { return _regionMaskRegionInWorld; }
			set { _regionMaskRegionInWorld = value; }
		}

		private bool _regionShroudGen;

		public bool RegionShroudGen {
			get { return _regionShroudGen; }
			set { _regionShroudGen = value; }
		}

		private bool _regionShroudVisibleInWorld;

		public bool RegionShroudVisibleInWorld {
			get { return _regionShroudVisibleInWorld; }
			set { _regionShroudVisibleInWorld = value; }
		}

		private bool _removeDestroyedItems;

		public bool RemoveDestroyedItems {
			get { return _removeDestroyedItems; }
			set { _removeDestroyedItems = value; }
		}

		private byte _renderChannel;

		public byte RenderChannel {
			get { return _renderChannel; }
			set { _renderChannel = value; }
		}

		private LSString _rollConditions;

		public LSString RollConditions {
			get { return _rollConditions; }
			set { _rollConditions = value; }
		}

		private bool _rotateImpact;

		public bool RotateImpact {
			get { return _rotateImpact; }
			set { _rotateImpact = value; }
		}

		private float _scale;

		public float Scale {
			get { return _scale; }
			set { _scale = value; }
		}

		private Tuple<float, float, float> _scrollingDirection;

		public Tuple<float, float, float> ScrollingDirection {
			get { return _scrollingDirection; }
			set { _scrollingDirection = value; }
		}

		private float _scrollingDistance;

		public float ScrollingDistance {
			get { return _scrollingDistance; }
			set { _scrollingDistance = value; }
		}

		private float _scrollingOffset;

		public float ScrollingOffset {
			get { return _scrollingOffset; }
			set { _scrollingOffset = value; }
		}

		private Tuple<float, float, float> _scrollingOrigin;

		public Tuple<float, float, float> ScrollingOrigin {
			get { return _scrollingOrigin; }
			set { _scrollingOrigin = value; }
		}

		private float _scrollingSpeed;

		public float ScrollingSpeed {
			get { return _scrollingSpeed; }
			set { _scrollingSpeed = value; }
		}

		private bool _secretRegionUnlocked;

		public bool SecretRegionUnlocked {
			get { return _secretRegionUnlocked; }
			set { _secretRegionUnlocked = value; }
		}

		private uint _seed;

		public uint Seed {
			get { return _seed; }
			set { _seed = value; }
		}

		private bool _seeThrough;

		public bool SeeThrough {
			get { return _seeThrough; }
			set { _seeThrough = value; }
		}

		private bool _shadow;

		public bool Shadow {
			get { return _shadow; }
			set { _shadow = value; }
		}

		private sbyte _shootThroughType;

		public sbyte ShootThroughType {
			get { return _shootThroughType; }
			set { _shootThroughType = value; }
		}

		private FixedString _shortHair;

		public FixedString ShortHair {
			get { return _shortHair; }
			set { _shortHair = value; }
		}

		private Tuple<float, float, float> _size;

		public Tuple<float, float, float> Size {
			get { return _size; }
			set { _size = value; }
		}

		private FixedString _softBodyCollisionTemplate;

		public FixedString SoftBodyCollisionTemplate {
			get { return _softBodyCollisionTemplate; }
			set { _softBodyCollisionTemplate = value; }
		}

		private short _soundAttenuation;

		public short SoundAttenuation {
			get { return _soundAttenuation; }
			set { _soundAttenuation = value; }
		}

		private FixedString _soundEvent;

		public FixedString SoundEvent {
			get { return _soundEvent; }
			set { _soundEvent = value; }
		}

		private FixedString _soundInitEvent;

		public FixedString SoundInitEvent {
			get { return _soundInitEvent; }
			set { _soundInitEvent = value; }
		}

		private byte _soundObjectIndex;

		public byte SoundObjectIndex {
			get { return _soundObjectIndex; }
			set { _soundObjectIndex = value; }
		}

		private LSString _speakerGroup;

		public LSString SpeakerGroup {
			get { return _speakerGroup; }
			set { _speakerGroup = value; }
		}

		private float _speed;

		public float Speed {
			get { return _speed; }
			set { _speed = value; }
		}

		private FixedString _spellSet;

		public FixedString SpellSet {
			get { return _spellSet; }
			set { _spellSet = value; }
		}

		private bool _spotSneakers;

		public bool SpotSneakers {
			get { return _spotSneakers; }
			set { _spotSneakers = value; }
		}

		private int _stagingType;

		public int StagingType {
			get { return _stagingType; }
			set { _stagingType = value; }
		}

		private float _startCombatRange;

		public float StartCombatRange {
			get { return _startCombatRange; }
			set { _startCombatRange = value; }
		}

		private bool _startingActive;

		public bool StartingActive {
			get { return _startingActive; }
			set { _startingActive = value; }
		}

		private bool _startingLoaded;

		public bool StartingLoaded {
			get { return _startingLoaded; }
			set { _startingLoaded = value; }
		}

		private FixedString _stats;

		public FixedString Stats {
			get { return _stats; }
			set { _stats = value; }
		}

		private bool _stayInAiHints;

		public bool StayInAiHints {
			get { return _stayInAiHints; }
			set { _stayInAiHints = value; }
		}

		private bool _storyItem;

		public bool StoryItem {
			get { return _storyItem; }
			set { _storyItem = value; }
		}

		private FixedString _subLevelName;

		public FixedString SubLevelName {
			get { return _subLevelName; }
			set { _subLevelName = value; }
		}

		private FixedString _summon;

		public FixedString Summon {
			get { return _summon; }
			set { _summon = value; }
		}

		private byte _surfaceCategory;

		public byte SurfaceCategory {
			get { return _surfaceCategory; }
			set { _surfaceCategory = value; }
		}

		private float _surfaceGrowTimer;

		public float SurfaceGrowTimer {
			get { return _surfaceGrowTimer; }
			set { _surfaceGrowTimer = value; }
		}

		private FixedString _target;

		public FixedString Target {
			get { return _target; }
			set { _target = value; }
		}

		private byte _team;

		public byte Team {
			get { return _team; }
			set { _team = value; }
		}

		private FixedString _templateAfterDestruction;

		public FixedString TemplateAfterDestruction {
			get { return _templateAfterDestruction; }
			set { _templateAfterDestruction = value; }
		}

		private FixedString _templateName;

		public FixedString TemplateName {
			get { return _templateName; }
			set { _templateName = value; }
		}

		private byte _textureMapping;

		public byte TextureMapping {
			get { return _textureMapping; }
			set { _textureMapping = value; }
		}

		private Tuple<float, float> _tiling;

		public Tuple<float, float> Tiling {
			get { return _tiling; }
			set { _tiling = value; }
		}

		private Guid _timeline;

		public Guid Timeline {
			get { return _timeline; }
			set { _timeline = value; }
		}

		private TranslatedString _title;

		public TranslatedString Title {
			get { return _title; }
			set { _title = value; }
		}

		private byte _tooltip;

		public byte Tooltip {
			get { return _tooltip; }
			set { _tooltip = value; }
		}

		private FixedString _trailFX;

		public FixedString TrailFX {
			get { return _trailFX; }
			set { _trailFX = value; }
		}

		private float _transitionDistance;

		public float TransitionDistance {
			get { return _transitionDistance; }
			set { _transitionDistance = value; }
		}

		private int _treasureLevel;

		public int TreasureLevel {
			get { return _treasureLevel; }
			set { _treasureLevel = value; }
		}

		private int _treasureLevelOverride;

		public int TreasureLevelOverride {
			get { return _treasureLevelOverride; }
			set { _treasureLevelOverride = value; }
		}

		private bool _treasureOnDestroy;

		public bool TreasureOnDestroy {
			get { return _treasureOnDestroy; }
			set { _treasureOnDestroy = value; }
		}

		private FixedString _triggerAtmosphere;

		public FixedString TriggerAtmosphere {
			get { return _triggerAtmosphere; }
			set { _triggerAtmosphere = value; }
		}

		private bool _triggerCameraLockPos;

		public bool TriggerCameraLockPos {
			get { return _triggerCameraLockPos; }
			set { _triggerCameraLockPos = value; }
		}

		private short _triggerCrimeArea;

		public short TriggerCrimeArea {
			get { return _triggerCrimeArea; }
			set { _triggerCrimeArea = value; }
		}

		private int _triggerGameCameraBehavior;

		public int TriggerGameCameraBehavior {
			get { return _triggerGameCameraBehavior; }
			set { _triggerGameCameraBehavior = value; }
		}

		private FixedString _triggerGizmoOverride;

		public FixedString TriggerGizmoOverride {
			get { return _triggerGizmoOverride; }
			set { _triggerGizmoOverride = value; }
		}

		private FixedString _triggerLighting;

		public FixedString TriggerLighting {
			get { return _triggerLighting; }
			set { _triggerLighting = value; }
		}

		private FixedString _triggerRegion;

		public FixedString TriggerRegion {
			get { return _triggerRegion; }
			set { _triggerRegion = value; }
		}

		private FixedString _triggerType;

		public FixedString TriggerType {
			get { return _triggerType; }
			set { _triggerType = value; }
		}

		private FixedString _type;

		public FixedString Type {
			get { return _type; }
			set { _type = value; }
		}

		private FixedString _unequipSound;

		public FixedString UnequipSound {
			get { return _unequipSound; }
			set { _unequipSound = value; }
		}

		private bool _unimportant;

		public bool Unimportant {
			get { return _unimportant; }
			set { _unimportant = value; }
		}

		private TranslatedString _unknownDescription;

		public TranslatedString UnknownDescription {
			get { return _unknownDescription; }
			set { _unknownDescription = value; }
		}

		private TranslatedString _unknownDisplayName;

		public TranslatedString UnknownDisplayName {
			get { return _unknownDisplayName; }
			set { _unknownDisplayName = value; }
		}

		private bool _useDOF;

		public bool UseDOF {
			get { return _useDOF; }
			set { _useDOF = value; }
		}

		private bool _useOnDistance;

		public bool UseOnDistance {
			get { return _useOnDistance; }
			set { _useOnDistance = value; }
		}

		private bool _usePartyLevelForTreasureLevel;

		public bool UsePartyLevelForTreasureLevel {
			get { return _usePartyLevelForTreasureLevel; }
			set { _usePartyLevelForTreasureLevel = value; }
		}

		private bool _useRemotely;

		public bool UseRemotely {
			get { return _useRemotely; }
			set { _useRemotely = value; }
		}

		private FixedString _useSound;

		public FixedString UseSound {
			get { return _useSound; }
			set { _useSound = value; }
		}

		private FixedString _uUID;

		public FixedString UUID {
			get { return _uUID; }
			set { _uUID = value; }
		}

		private float _vFXScale;

		public float VFXScale {
			get { return _vFXScale; }
			set { _vFXScale = value; }
		}

		private FixedString _visualSetResourceID;

		public FixedString VisualSetResourceID {
			get { return _visualSetResourceID; }
			set { _visualSetResourceID = value; }
		}

		private FixedString _visualTemplate;

		public FixedString VisualTemplate {
			get { return _visualTemplate; }
			set { _visualTemplate = value; }
		}

		private FixedString _vocalAlertResourceID;

		public FixedString VocalAlertResourceID {
			get { return _vocalAlertResourceID; }
			set { _vocalAlertResourceID = value; }
		}

		private FixedString _vocalAngryResourceID;

		public FixedString VocalAngryResourceID {
			get { return _vocalAngryResourceID; }
			set { _vocalAngryResourceID = value; }
		}

		private FixedString _vocalAnticipationResourceID;

		public FixedString VocalAnticipationResourceID {
			get { return _vocalAnticipationResourceID; }
			set { _vocalAnticipationResourceID = value; }
		}

		private FixedString _vocalAttackResourceID;

		public FixedString VocalAttackResourceID {
			get { return _vocalAttackResourceID; }
			set { _vocalAttackResourceID = value; }
		}

		private FixedString _vocalAwakeResourceID;

		public FixedString VocalAwakeResourceID {
			get { return _vocalAwakeResourceID; }
			set { _vocalAwakeResourceID = value; }
		}

		private FixedString _vocalBoredResourceID;

		public FixedString VocalBoredResourceID {
			get { return _vocalBoredResourceID; }
			set { _vocalBoredResourceID = value; }
		}

		private FixedString _vocalDeathResourceID;

		public FixedString VocalDeathResourceID {
			get { return _vocalDeathResourceID; }
			set { _vocalDeathResourceID = value; }
		}

		private FixedString _vocalDodgeResourceID;

		public FixedString VocalDodgeResourceID {
			get { return _vocalDodgeResourceID; }
			set { _vocalDodgeResourceID = value; }
		}

		private FixedString _vocalEffortsResourceID;

		public FixedString VocalEffortsResourceID {
			get { return _vocalEffortsResourceID; }
			set { _vocalEffortsResourceID = value; }
		}

		private FixedString _vocalExhaustedResourceID;

		public FixedString VocalExhaustedResourceID {
			get { return _vocalExhaustedResourceID; }
			set { _vocalExhaustedResourceID = value; }
		}

		private FixedString _vocalFallResourceID;

		public FixedString VocalFallResourceID {
			get { return _vocalFallResourceID; }
			set { _vocalFallResourceID = value; }
		}

		private FixedString _vocalInitiativeResourceID;

		public FixedString VocalInitiativeResourceID {
			get { return _vocalInitiativeResourceID; }
			set { _vocalInitiativeResourceID = value; }
		}

		private FixedString _vocalLaughterResourceID;

		public FixedString VocalLaughterResourceID {
			get { return _vocalLaughterResourceID; }
			set { _vocalLaughterResourceID = value; }
		}

		private FixedString _vocalPainResourceID;

		public FixedString VocalPainResourceID {
			get { return _vocalPainResourceID; }
			set { _vocalPainResourceID = value; }
		}

		private FixedString _vocalRebornResourceID;

		public FixedString VocalRebornResourceID {
			get { return _vocalRebornResourceID; }
			set { _vocalRebornResourceID = value; }
		}

		private FixedString _vocalRecoverResourceID;

		public FixedString VocalRecoverResourceID {
			get { return _vocalRecoverResourceID; }
			set { _vocalRecoverResourceID = value; }
		}

		private FixedString _vocalRelaxedResourceID;

		public FixedString VocalRelaxedResourceID {
			get { return _vocalRelaxedResourceID; }
			set { _vocalRelaxedResourceID = value; }
		}

		private FixedString _vocalShoutResourceID;

		public FixedString VocalShoutResourceID {
			get { return _vocalShoutResourceID; }
			set { _vocalShoutResourceID = value; }
		}

		private FixedString _vocalSnoreResourceID;

		public FixedString VocalSnoreResourceID {
			get { return _vocalSnoreResourceID; }
			set { _vocalSnoreResourceID = value; }
		}

		private FixedString _vocalSpawnResourceID;

		public FixedString VocalSpawnResourceID {
			get { return _vocalSpawnResourceID; }
			set { _vocalSpawnResourceID = value; }
		}

		private FixedString _vocalVictoryResourceID;

		public FixedString VocalVictoryResourceID {
			get { return _vocalVictoryResourceID; }
			set { _vocalVictoryResourceID = value; }
		}

		private FixedString _vocalWeakResourceID;

		public FixedString VocalWeakResourceID {
			get { return _vocalWeakResourceID; }
			set { _vocalWeakResourceID = value; }
		}

		private float _volumetricLightCollisionProbability;

		public float VolumetricLightCollisionProbability {
			get { return _volumetricLightCollisionProbability; }
			set { _volumetricLightCollisionProbability = value; }
		}

		private float _volumetricLightIntensity;

		public float VolumetricLightIntensity {
			get { return _volumetricLightIntensity; }
			set { _volumetricLightIntensity = value; }
		}

		private bool _wadable;

		public bool Wadable {
			get { return _wadable; }
			set { _wadable = value; }
		}

		private bool _walkOn;

		public bool WalkOn {
			get { return _walkOn; }
			set { _walkOn = value; }
		}

		private bool _walkThrough;

		public bool WalkThrough {
			get { return _walkThrough; }
			set { _walkThrough = value; }
		}

		private bool _zoom;

		public bool Zoom {
			get { return _zoom; }
			set { _zoom = value; }
		}
		#endregion
	}
}
