/// <summary>
/// The cursor modes.
/// </summary>
namespace bg3_modders_multitool.Enums.ValueLists
{
    public enum CursorMode
    {
        None,
        System,
        Arrow,
        Arrow_Warning,
        Bow,
        Bow_Warning,
        Bow_Ground,
        Wand,
        Wand_Warning,
        Wand_Ground,
        BackStab,
        BackStab_Warning,
        Cast,
        Cast_Warning,
        Combine,
        Combine_Warning,
        Combine_Invalid,
        Cross,
        Identify,
        Identify_Warning,
        ItemMove,
        ItemMove_Warning,
        ItemUse,
        ItemUse_Warning,
        ItemPickup,
        ItemPickup_Warning,
        Lock,
        Lock_Warning,
        Melee,
        Melee_Warning,
        Melee_Ground,
        OpenContainer,
        OpenContainer_Warning,
        OpenContainer_New,
        OpenDoor,
        OpenDoor_Warning,
        PickPocket,
        PickPocket_Warning,
        Repair,
        Repair_Warning,
        Shovel,
        Shovel_Warning,
        Talk,
        Talk_Warning,
        Walk,
        Walk_Warning,
        CameraRotation,
        Listen,
        Listen_Warning
    }
}